name: Deploy a Django app to App Service #touch

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    # Set Python version (https://github.com/actions/setup-python)
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7.4' 
        architecture: 'x64' # What's our bitness on Linux?

    - name: Install modules
      run: |
        python3 -m venv antenv
        source antenv/bin/activate
        pip install -r requirements.txt

    # Finally, deploy the app to App Service (https://github.com/Azure/webapps-deploy)
    - uses: azure/webapps-deploy@v1
      with:
        app-name: sch1008ptdemo
        publish-profile: ${{ secrets.SCHPYTHONAPP }}
